### ISSUE TITLE
Deprecate CONTRIBUTING.md for new CONTRIBUTING.template.md and CONTRIBUTING.standards.md

### ISSUE THREAD

**Issue by maoo** [finos/software-project-blueprint#20]
- [ ] Shall https://github.com/finos/project-blueprint/blob/master/CONTRIBUTING.md be deprecated in favour of https://github.com/finos/project-blueprint/blob/master/CONTRIBUTING.standards.md and https://github.com/finos/project-blueprint/blob/master/CONTRIBUTING.template.md ?
- [ ] Update any Wiki/microsite/issue-template that points to the old CONTRIBUTING.md file

**Comment by rikoe** [comment]
This section of the template refers to co-located files which aren't present in the blueprint (or after cloning the blueprint), leading to 404s:

```markdown
# {project name} Contribution and Governance Policies

This document describes the contribution process and governance policies of the FINOS {project name} project. 
The project is also governed by the [Linux Foundation Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), 
and the FINOS [IP Policy](IP-Policy.pdf), [Code of Conduct](Code-of-Conduct.md), [Collaborative Principles]
(Collaborative-Principles.md), and [Meeting Procedures](Meeting-Procedures.md).
```

I have modified it to the following when bringing it across, so that the links work:
```markdown
# {project name} Contribution and Governance Policies

This document describes the contribution process and governance policies of the FINOS FDC3 project. The project is also 
governed by the [Linux Foundation Antitrust Policy], and the FINOS [IP Policy], [Code of Conduct], [Collaborative 
Principles], and [Meeting Procedures].

[Linux Foundation Antitrust Policy]: https://www.linuxfoundation.org/antitrust-policy/
[IP Policy]: https://github.com/finos/community/blob/master/governance/IP-Policy.pdf
[Code of Conduct]: https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md
[Collaborative Principles]: https://github.com/finos/community/blob/master/governance/Collaborative-Principles.md
[Meeting Procedures]: https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md
```
It is worth noting that the same is true of https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md, which also links to the same files co-located in the local folder, but the actual files being linked to are in the _parent_ folder (`https://github.com/finos/community/blob/master/governance`), so those links are broken as well.

In both cases, I believe the solution would just be to use absolute ULRs for the FINOS governance documents, which would mean they will continue to work regardless of where/how they are cloned, and what files accompany them.

**Comment by rikoe** [comment]
It is also worth considering what to do for a project which is _both_ a standards and a software project, which is effectively what FDC3 has become now that we publish an NPM package (although the repository has always had code files as well...).

I have adopted `CONTRIBUTING.template.md` as `CONTRIBUTING.md` and `CONTRIBUTING.standards.md` as `CONTRIBUTING.standards.md`.

See https://github.com/finos/FDC3/pull/276.

Please let me know if this is not the correct approach.

**Comment by mcleo-d** [comment]
Hi @rikoe

Thanks for reporting the broken PDF links in CONTRIBUTING.md 👍 

I have resolved the issue by raising the following PR https://github.com/finos/project-blueprint/pull/21 that follows your approach of linking to the documents in the FINOS Community repository. I have also commented here https://github.com/finos/FDC3/pull/276#discussion_r512008110.

With regards to https://github.com/finos/project-blueprint/issues/20#issuecomment-716511373, I suggest consuming [Standards Projects - CONTRIBUTING.standards.md](https://github.com/finos/community/tree/master/governance/Standards-Projects) into the `root` of FDC3 and link from `CONTRIBUTING.md` to `CONTRIBUTING.standards.md` in the document markdown.

In the meantime, I'll reach out to @mindthegab to investigate whether the documents should be merged.

James.
